# Generated by Django 4.2.1 on 2023-05-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_books_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book'),
        ),
    ]
