# Generated by Django 4.2.1 on 2023-05-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_review_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Books',
            new_name='book',
        ),
    ]
