# Generated by Django 4.2.1 on 2023-05-22 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_books_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
