# Generated by Django 4.2.1 on 2023-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
