# Generated by Django 4.2.1 on 2023-05-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_review_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='Book_id',
            new_name='book_id',
        ),
    ]
