# Generated by Django 4.2 on 2023-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_book_id_rental_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cataloge',
            field=models.CharField(blank=True, choices=[('Art', 'art'), ('Music', 'Music'), ('Luctcer', 'Luctcer'), ('Since', 'Since'), ('Technology', 'Technology')], max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='publishe_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_information',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
