# Generated by Django 4.2.1 on 2023-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_cataloge_book_publishe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cataloge',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('music', 'Music'), ('luctcer', 'Luctcer'), ('since', 'Since'), ('technology', 'Technology')], max_length=50),
        ),
    ]
