# Generated by Django 4.2.1 on 2023-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_cataloge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cataloge',
            field=models.CharField(blank=True, choices=[('Art', 'art'), ('Music', 'music'), ('Luctcer', 'luctcer'), ('Since', 'since'), ('Technology', 'technology')], max_length=50),
        ),
    ]
