# Generated by Django 4.2.1 on 2023-06-18 11:11

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='date_to',
            field=models.DateField(default=books.models.default_due_date),
        ),
    ]
